name: emmo
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^3.8.0
  cloud_firestore: ^5.5.0
  firebase_auth: ^5.3.3
  mailer: ^6.2.0
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  google_maps_flutter: ^2.10.0
  image_picker: ^1.0.0
  image_cropper: ^8.0.2
  http: ^1.2.2
  webview_flutter: ^4.8.0
  intl: ^0.18.1
  audioplayers: ^6.0.0
  provider: ^6.1.1
  pdf: ^3.10.0
  path_provider: ^2.1.1
  open_file: ^3.3.1
  printing: ^5.7.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:

 
  uses-material-design: true
  assets:
    - assets/images/mail.jpg
    - assets/sound1.mp3
    - assets/sound2.mp3
    - assets/sound3.mp3
    - assets/sound4.mp3
    - assets/sound5.mp3

  